### ISSUE TITLE
Macro sailfish_build doesn't appear to be there any more

### ISSUE THREAD

**Issue by gabrielgg** [rinigus/pkg-libpostal#3]
So, things like "%define static_only_build 1" don't get defined and dependencies like "pkg-config" are required in the sailfish/mer SDK.
I am building from the pkg-libpostal directory directly (so I call mb2 with "-s rpm/libpostal.spec" - hope I am not breaking it this way, as otherwise I don't know what directory to start from (as per README).
If indeed you used to decide whether it was a sailfish build or not depending on the existence of that macro, then I wouldn't know how to fix this, besides perhaps testing the `uname` or something like that.

**Comment by rinigus** [comment]
I have fixed pkg-config requirement - that seems not to be needed anymore. As for `sailfish_build`, it is defined in tbuilder config file. will write regarding it in other issue
